import { test, expect } from '@playwright/test'

test.describe('Smart Summary App E2E', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('has title and description', async ({ page }) => {
    await expect(page.getByRole('heading', { name: /smart summary app/i })).toBeVisible()
    await expect(page.getByText(/transform long text into concise summaries/i)).toBeVisible()
  })

  test('displays the summary form', async ({ page }) => {
    await expect(page.getByLabel(/enter your text to summarize/i)).toBeVisible()
    await expect(page.getByRole('button', { name: /generate summary/i })).toBeVisible()
  })

  test('submit button is disabled with empty text', async ({ page }) => {
    const submitButton = page.getByRole('button', { name: /generate summary/i })
    await expect(submitButton).toBeDisabled()
  })

  test('submit button is disabled with text below minimum length', async ({ page }) => {
    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('Short')

    const submitButton = page.getByRole('button', { name: /generate summary/i })
    await expect(submitButton).toBeDisabled()
  })

  test('submit button is enabled with valid text', async ({ page }) => {
    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('This is a valid text input that meets the minimum length requirement.')

    const submitButton = page.getByRole('button', { name: /generate summary/i })
    await expect(submitButton).toBeEnabled()
  })

  test('character count updates as user types', async ({ page }) => {
    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('Hello World')

    await expect(page.getByText(/11/)).toBeVisible()
  })

  test('loads example text when button clicked', async ({ page }) => {
    await page.getByText(/load example text/i).click()

    const textarea = page.getByLabel(/enter your text to summarize/i)
    const value = await textarea.inputValue()
    expect(value.length).toBeGreaterThan(100)
    expect(value).toContain('Artificial Intelligence')
  })

  test('clears text when clear button clicked', async ({ page }) => {
    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('Some text to clear')

    await page.getByText(/clear/i).click()

    const value = await textarea.inputValue()
    expect(value).toBe('')
  })

  test('shows loading state when submitting', async ({ page }) => {
    // Mock the API to delay response
    await page.route('**/api/summarize', async route => {
      await new Promise(resolve => setTimeout(resolve, 100))
      await route.fulfill({
        status: 200,
        headers: { 'Content-Type': 'text/event-stream' },
        body: 'data: Test summary\n\ndata: [DONE]\n\n',
      })
    })

    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('This is a test text for summarization that meets minimum requirements.')

    const submitButton = page.getByRole('button', { name: /generate summary/i })
    await submitButton.click()

    await expect(page.getByText(/generating summary/i)).toBeVisible()
  })

  test('displays summary after successful submission', async ({ page }) => {
    // Mock successful API response
    await page.route('**/api/summarize', async route => {
      await route.fulfill({
        status: 200,
        headers: { 'Content-Type': 'text/event-stream' },
        body: 'data: This is a test summary generated by the AI.\n\ndata: [DONE]\n\n',
      })
    })

    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('This is a long article about artificial intelligence and machine learning technologies.')

    const submitButton = page.getByRole('button', { name: /generate summary/i })
    await submitButton.click()

    // Wait for summary to appear
    await expect(page.getByRole('heading', { name: /summary/i })).toBeVisible()
    await expect(page.getByText(/this is a test summary/i)).toBeVisible()
  })

  test('displays error message on API failure', async ({ page }) => {
    // Mock API error
    await page.route('**/api/summarize', async route => {
      await route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({ detail: 'Internal server error' }),
      })
    })

    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('This text will trigger an error for testing purposes.')

    const submitButton = page.getByRole('button', { name: /generate summary/i })
    await submitButton.click()

    await expect(page.getByText(/error/i)).toBeVisible()
  })

  test('copy button works after summary is generated', async ({ page }) => {
    // Mock successful API response
    await page.route('**/api/summarize', async route => {
      await route.fulfill({
        status: 200,
        headers: { 'Content-Type': 'text/event-stream' },
        body: 'data: Test summary to copy\n\ndata: [DONE]\n\n',
      })
    })

    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('Text for testing copy functionality with proper length.')

    await page.getByRole('button', { name: /generate summary/i }).click()

    // Wait for summary
    await expect(page.getByText(/test summary to copy/i)).toBeVisible()

    // Grant clipboard permissions
    await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])

    // Click copy button
    await page.getByRole('button', { name: /copy/i }).click()

    // Check for "Copied!" feedback
    await expect(page.getByText(/copied!/i)).toBeVisible()
  })

  test('shows disclaimer after summary is generated', async ({ page }) => {
    await page.route('**/api/summarize', async route => {
      await route.fulfill({
        status: 200,
        headers: { 'Content-Type': 'text/event-stream' },
        body: 'data: Summary text\n\ndata: [DONE]\n\n',
      })
    })

    const textarea = page.getByLabel(/enter your text to summarize/i)
    await textarea.fill('Text for testing disclaimer visibility.')

    await page.getByRole('button', { name: /generate summary/i }).click()

    await expect(page.getByText(/this summary was generated using ai/i)).toBeVisible()
  })

  test('handles multiple summarization requests', async ({ page }) => {
    let requestCount = 0

    await page.route('**/api/summarize', async route => {
      requestCount++
      await route.fulfill({
        status: 200,
        headers: { 'Content-Type': 'text/event-stream' },
        body: `data: Summary ${requestCount}\n\ndata: [DONE]\n\n`,
      })
    })

    const textarea = page.getByLabel(/enter your text to summarize/i)

    // First request
    await textarea.fill('First text for summarization testing.')
    await page.getByRole('button', { name: /generate summary/i }).click()
    await expect(page.getByText(/summary 1/i)).toBeVisible()

    // Second request
    await textarea.fill('Second text for summarization testing.')
    await page.getByRole('button', { name: /generate summary/i }).click()
    await expect(page.getByText(/summary 2/i)).toBeVisible()

    expect(requestCount).toBe(2)
  })
})
